

let data = {
    performanceTrends :  [
        {
          "name": "水煤浆",
          "yAxisIndex": 0,
          "valueList": [
            {
            "value": "91000",
            "xAxis": "9-9"
          }, {
            "value": "83000",
            "xAxis": "9-10"
          }, {
            "value": "97000",
            "xAxis": "9-11"
          }, {
            "value": "75000",
            "xAxis": "9-12"
          }, {
            "value": "65000",
            "xAxis": "9-13"
          }, {
            "value": "55000",
            "xAxis": "9-14"
          }, {
            "value": "64000",
            "xAxis": "9-15"
          }, {
            "value": "72000",
            "xAxis": "9-16"
          }, {
            "value": "91000",
            "xAxis": "9-17"
          }, {
            "value": "83000",
            "xAxis": "9-18"
          }, {
            "value": "97000",
            "xAxis": "9-19"
          }, {
            "value": "75000",
            "xAxis": "9-20"
          }, {
            "value": "65000",
            "xAxis": "9-21"
          }, {
            "value": "55000",
            "xAxis": "9-22"
          }, {
            "value": "64000",
            "xAxis": "9-23"
          }, {
            "value": "72000",
            "xAxis": "9-24"
          },{
            "value": "91000",
            "xAxis": "9-25"
          }, {
            "value": "83000",
            "xAxis": "9-26"
          }, {
            "value": "97000",
            "xAxis": "9-27"
          }, {
            "value": "75000",
            "xAxis": "9-28"
          }, {
            "value": "65000",
            "xAxis": "9-29"
          }, {
            "value": "55000",
            "xAxis": "9-30"
          }, {
            "value": "64000",
            "xAxis": "10-1"
          }, {
            "value": "72000",
            "xAxis": "10-2"
          }, {
            "value": "91000",
            "xAxis": "10-3"
          }, {
            "value": "83000",
            "xAxis": "10-4"
          }, {
            "value": "97000",
            "xAxis": "10-5"
          }, {
            "value": "75000",
            "xAxis": "10-6"
          }, {
            "value": "65000",
            "xAxis": "10-7"
          }, {
            "value": "22000",
            "xAxis": "10-8"
          }]
        }, {
            "name": "负荷",
            "yAxisIndex": 1,
            "valueList": [
              {
              "value": "91000",
              "xAxis": "9-9"
            }, {
              "value": "83000",
              "xAxis": "9-10"
            }, {
              "value": "97000",
              "xAxis": "9-11"
            }, {
              "value": "75000",
              "xAxis": "9-12"
            }, {
              "value": "65000",
              "xAxis": "9-13"
            }, {
              "value": "55000",
              "xAxis": "9-14"
            }, {
              "value": "64000",
              "xAxis": "9-15"
            }, {
              "value": "72000",
              "xAxis": "9-16"
            }, {
              "value": "91000",
              "xAxis": "9-17"
            }, {
              "value": "83000",
              "xAxis": "9-18"
            }, {
              "value": "97000",
              "xAxis": "9-19"
            }, {
              "value": "75000",
              "xAxis": "9-20"
            }, {
              "value": "65000",
              "xAxis": "9-21"
            }, {
              "value": "55000",
              "xAxis": "9-22"
            }, {
              "value": "64000",
              "xAxis": "9-23"
            }, {
              "value": "72000",
              "xAxis": "9-24"
            },{
              "value": "91000",
              "xAxis": "9-25"
            }, {
              "value": "83000",
              "xAxis": "9-26"
            }, {
              "value": "97000",
              "xAxis": "9-27"
            }, {
              "value": "75000",
              "xAxis": "9-28"
            }, {
              "value": "65000",
              "xAxis": "9-29"
            }, {
              "value": "55000",
              "xAxis": "9-30"
            }, {
              "value": "64000",
              "xAxis": "10-1"
            }, {
              "value": "72000",
              "xAxis": "10-2"
            }, {
              "value": "91000",
              "xAxis": "10-3"
            }, {
              "value": "83000",
              "xAxis": "10-4"
            }, {
              "value": "97000",
              "xAxis": "10-5"
            }, {
              "value": "75000",
              "xAxis": "10-6"
            }, {
              "value": "65000",
              "xAxis": "10-7"
            }, {
              "value": "22000",
              "xAxis": "10-8"
            }]
          }, {
            "name": "效率",
            "yAxisIndex": 2,
            "valueList": [{
              "value": "47",
              "xAxis": "9-9"
            }, {
              "value": "77",
              "xAxis": "9-10"
            }, {
              "value": "86",
              "xAxis": "9-11"
            }, {
              "value": "94",
              "xAxis": "9-12"
            }, {
              "value": "69",
              "xAxis": "9-13"
            }, {
              "value": "89",
              "xAxis": "9-14"
            }, {
              "value": "90",
              "xAxis": "9-15"
            }, {
              "value": "95",
              "xAxis": "9-16"
            }, {
              "value": "98",
              "xAxis": "9-17"
            }, {
              "value": "57",
              "xAxis": "9-18"
            }, {
              "value": "74",
              "xAxis": "9-19"
            }, {
              "value": "36",
              "xAxis": "9-20"
            }, {
              "value": "57",
              "xAxis": "9-21"
            }, {
              "value": "77",
              "xAxis": "9-22"
            }, {
              "value": "87",
              "xAxis": "9-23"
            }, {
              "value": "96",
              "xAxis": "9-24"
            },{
              "value": "46",
              "xAxis": "9-25"
            }, {
              "value": "72",
              "xAxis": "9-26"
            }, {
              "value": "47",
              "xAxis": "9-27"
            }, {
              "value": "67",
              "xAxis": "9-28"
            }, {
              "value": "33",
              "xAxis": "9-29"
            }, {
              "value": "93",
              "xAxis": "9-30"
            }, {
              "value": "49",
              "xAxis": "10-1"
            }, {
              "value": "69",
              "xAxis": "10-2"
            }, {
              "value": "77",
              "xAxis": "10-3"
            }, {
              "value": "66",
              "xAxis": "10-4"
            }, {
              "value": "48",
              "xAxis": "10-5"
            }, {
              "value": "90",
              "xAxis": "10-6"
            }, {
              "value": "78",
              "xAxis": "10-7"
            }, {
              "value": "55",
              "xAxis": "10-8"
            }
            ]
          }]
}


export default data